// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndpointTest(arg1) {
  return window['go']['main']['App']['EndpointTest'](arg1);
}

export function ShellBootstrap() {
  return window['go']['main']['App']['ShellBootstrap']();
}

export function ShellEmitDiagnosticsProbe() {
  return window['go']['main']['App']['ShellEmitDiagnosticsProbe']();
}
