// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';
import {appshell} from '../models';

export function CallCancel(arg1:contracts.CallCancelInput):Promise<contracts.CallCancelResponse>;

export function CallInvokeUnary(arg1:contracts.CallInvokeUnaryInput):Promise<contracts.CallInvokeUnaryResponse>;

export function CallStartStream(arg1:contracts.CallStartStreamInput):Promise<contracts.CallStartStreamResponse>;

export function CatalogLoadFromProtoSources(arg1:contracts.CatalogLoadFromProtoSourcesInput):Promise<contracts.CatalogLoadFromProtoSourcesResponse>;

export function CatalogLoadFromReflection(arg1:contracts.CatalogLoadFromReflectionInput):Promise<contracts.CatalogLoadFromReflectionResponse>;

export function EndpointTest(arg1:contracts.EndpointTestInput):Promise<contracts.EndpointTestResponse>;

export function HistoryGet(arg1:string):Promise<contracts.HistoryGetResponse>;

export function HistoryList(arg1:contracts.HistoryListInput):Promise<contracts.HistoryListResponse>;

export function RequestSave(arg1:contracts.RequestSaveInput):Promise<contracts.RequestSaveResponse>;

export function ShellBootstrap():Promise<appshell.BootstrapResponse>;

export function ShellEmitDiagnosticsProbe():Promise<appshell.ProbeResponse>;

export function WorkspaceCreate(arg1:contracts.WorkspaceCreateInput):Promise<contracts.WorkspaceResponse>;

export function WorkspaceOpen(arg1:string):Promise<contracts.WorkspaceResponse>;

export function WorkspaceSave(arg1:contracts.WorkspaceSaveInput):Promise<contracts.WorkspaceResponse>;

export function WorkspaceValidate(arg1:contracts.WorkspaceValidateInput):Promise<contracts.WorkspaceValidateResponse>;
