// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallCancel(arg1) {
  return window['go']['main']['App']['CallCancel'](arg1);
}

export function CallHalfClose(arg1) {
  return window['go']['main']['App']['CallHalfClose'](arg1);
}

export function CallInvokeUnary(arg1) {
  return window['go']['main']['App']['CallInvokeUnary'](arg1);
}

export function CallSendMessage(arg1) {
  return window['go']['main']['App']['CallSendMessage'](arg1);
}

export function CallStartStream(arg1) {
  return window['go']['main']['App']['CallStartStream'](arg1);
}

export function CatalogLoadFromProtoSources(arg1) {
  return window['go']['main']['App']['CatalogLoadFromProtoSources'](arg1);
}

export function CatalogLoadFromReflection(arg1) {
  return window['go']['main']['App']['CatalogLoadFromReflection'](arg1);
}

export function DiagnosticsExport(arg1) {
  return window['go']['main']['App']['DiagnosticsExport'](arg1);
}

export function DialogSelectMaterialFile() {
  return window['go']['main']['App']['DialogSelectMaterialFile']();
}

export function DialogSelectProtoDirectory() {
  return window['go']['main']['App']['DialogSelectProtoDirectory']();
}

export function DialogSelectProtoFiles() {
  return window['go']['main']['App']['DialogSelectProtoFiles']();
}

export function DialogSelectWorkspaceCreatePath() {
  return window['go']['main']['App']['DialogSelectWorkspaceCreatePath']();
}

export function DialogSelectWorkspaceOpenPath() {
  return window['go']['main']['App']['DialogSelectWorkspaceOpenPath']();
}

export function EndpointTest(arg1) {
  return window['go']['main']['App']['EndpointTest'](arg1);
}

export function GitHubWorkspaceLink(arg1) {
  return window['go']['main']['App']['GitHubWorkspaceLink'](arg1);
}

export function GitHubWorkspacePull(arg1) {
  return window['go']['main']['App']['GitHubWorkspacePull'](arg1);
}

export function GitHubWorkspacePush(arg1) {
  return window['go']['main']['App']['GitHubWorkspacePush'](arg1);
}

export function GitHubWorkspaceSetToken(arg1) {
  return window['go']['main']['App']['GitHubWorkspaceSetToken'](arg1);
}

export function GitHubWorkspaceStatus() {
  return window['go']['main']['App']['GitHubWorkspaceStatus']();
}

export function GitHubWorkspaceUnlink() {
  return window['go']['main']['App']['GitHubWorkspaceUnlink']();
}

export function HistoryGet(arg1) {
  return window['go']['main']['App']['HistoryGet'](arg1);
}

export function HistoryList(arg1) {
  return window['go']['main']['App']['HistoryList'](arg1);
}

export function MaterialRegisterFile(arg1) {
  return window['go']['main']['App']['MaterialRegisterFile'](arg1);
}

export function RequestDelete(arg1) {
  return window['go']['main']['App']['RequestDelete'](arg1);
}

export function RequestGet(arg1) {
  return window['go']['main']['App']['RequestGet'](arg1);
}

export function RequestSave(arg1) {
  return window['go']['main']['App']['RequestSave'](arg1);
}

export function ShellBootstrap() {
  return window['go']['main']['App']['ShellBootstrap']();
}

export function ShellEmitDiagnosticsProbe() {
  return window['go']['main']['App']['ShellEmitDiagnosticsProbe']();
}

export function UpdateCheck() {
  return window['go']['main']['App']['UpdateCheck']();
}

export function WorkspaceActive() {
  return window['go']['main']['App']['WorkspaceActive']();
}

export function WorkspaceClose() {
  return window['go']['main']['App']['WorkspaceClose']();
}

export function WorkspaceCreate(arg1) {
  return window['go']['main']['App']['WorkspaceCreate'](arg1);
}

export function WorkspaceDelete() {
  return window['go']['main']['App']['WorkspaceDelete']();
}

export function WorkspaceOpen(arg1) {
  return window['go']['main']['App']['WorkspaceOpen'](arg1);
}

export function WorkspaceSave(arg1) {
  return window['go']['main']['App']['WorkspaceSave'](arg1);
}

export function WorkspaceValidate(arg1) {
  return window['go']['main']['App']['WorkspaceValidate'](arg1);
}
