// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallCancel(arg1) {
  return window['go']['main']['App']['CallCancel'](arg1);
}

export function CallInvokeUnary(arg1) {
  return window['go']['main']['App']['CallInvokeUnary'](arg1);
}

export function CallStartStream(arg1) {
  return window['go']['main']['App']['CallStartStream'](arg1);
}

export function CatalogLoadFromProtoSources(arg1) {
  return window['go']['main']['App']['CatalogLoadFromProtoSources'](arg1);
}

export function CatalogLoadFromReflection(arg1) {
  return window['go']['main']['App']['CatalogLoadFromReflection'](arg1);
}

export function EndpointTest(arg1) {
  return window['go']['main']['App']['EndpointTest'](arg1);
}

export function HistoryGet(arg1) {
  return window['go']['main']['App']['HistoryGet'](arg1);
}

export function HistoryList(arg1) {
  return window['go']['main']['App']['HistoryList'](arg1);
}

export function RequestSave(arg1) {
  return window['go']['main']['App']['RequestSave'](arg1);
}

export function ShellBootstrap() {
  return window['go']['main']['App']['ShellBootstrap']();
}

export function ShellEmitDiagnosticsProbe() {
  return window['go']['main']['App']['ShellEmitDiagnosticsProbe']();
}

export function WorkspaceCreate(arg1) {
  return window['go']['main']['App']['WorkspaceCreate'](arg1);
}

export function WorkspaceOpen(arg1) {
  return window['go']['main']['App']['WorkspaceOpen'](arg1);
}

export function WorkspaceSave(arg1) {
  return window['go']['main']['App']['WorkspaceSave'](arg1);
}

export function WorkspaceValidate(arg1) {
  return window['go']['main']['App']['WorkspaceValidate'](arg1);
}
