// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';
import {appshell} from '../models';

export function CatalogLoadFromReflection(arg1:contracts.CatalogLoadFromReflectionInput):Promise<contracts.CatalogLoadFromReflectionResponse>;

export function EndpointTest(arg1:contracts.EndpointTestInput):Promise<contracts.EndpointTestResponse>;

export function ShellBootstrap():Promise<appshell.BootstrapResponse>;

export function ShellEmitDiagnosticsProbe():Promise<appshell.ProbeResponse>;
