// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';
import {appshell} from '../models';

export function CallCancel(arg1:contracts.CallCancelInput):Promise<contracts.CallCancelResponse>;

export function CallHalfClose(arg1:contracts.CallHalfCloseInput):Promise<contracts.CallHalfCloseResponse>;

export function CallInvokeUnary(arg1:contracts.CallInvokeUnaryInput):Promise<contracts.CallInvokeUnaryResponse>;

export function CallSendMessage(arg1:contracts.CallSendMessageInput):Promise<contracts.CallSendMessageResponse>;

export function CallStartStream(arg1:contracts.CallStartStreamInput):Promise<contracts.CallStartStreamResponse>;

export function CatalogLoadFromProtoSources(arg1:contracts.CatalogLoadFromProtoSourcesInput):Promise<contracts.CatalogLoadFromProtoSourcesResponse>;

export function CatalogLoadFromReflection(arg1:contracts.CatalogLoadFromReflectionInput):Promise<contracts.CatalogLoadFromReflectionResponse>;

export function DiagnosticsExport(arg1:contracts.DiagnosticsExportInput):Promise<contracts.DiagnosticsExportResponse>;

export function DialogSelectMaterialFile():Promise<string>;

export function DialogSelectProtoDirectory():Promise<string>;

export function DialogSelectProtoFiles():Promise<Array<string>>;

export function DialogSelectWorkspaceCreatePath():Promise<string>;

export function DialogSelectWorkspaceOpenPath():Promise<string>;

export function EndpointTest(arg1:contracts.EndpointTestInput):Promise<contracts.EndpointTestResponse>;

export function GitHubWorkspaceLink(arg1:contracts.GitHubWorkspaceLinkInput):Promise<contracts.GitHubSyncResponse>;

export function GitHubWorkspacePull(arg1:contracts.GitHubSyncActionInput):Promise<contracts.GitHubSyncResponse>;

export function GitHubWorkspacePush(arg1:contracts.GitHubSyncActionInput):Promise<contracts.GitHubSyncResponse>;

export function GitHubWorkspaceSetToken(arg1:contracts.GitHubWorkspaceCredentialInput):Promise<contracts.GitHubSyncResponse>;

export function GitHubWorkspaceStatus():Promise<contracts.GitHubSyncResponse>;

export function GitHubWorkspaceUnlink():Promise<contracts.GitHubSyncResponse>;

export function HistoryGet(arg1:string):Promise<contracts.HistoryGetResponse>;

export function HistoryList(arg1:contracts.HistoryListInput):Promise<contracts.HistoryListResponse>;

export function MaterialRegisterFile(arg1:contracts.MaterialRegisterFileInput):Promise<contracts.MaterialRegisterFileResponse>;

export function RequestDelete(arg1:contracts.RequestDeleteInput):Promise<contracts.RequestDeleteResponse>;

export function RequestGet(arg1:contracts.RequestGetInput):Promise<contracts.RequestGetResponse>;

export function RequestSave(arg1:contracts.RequestSaveInput):Promise<contracts.RequestSaveResponse>;

export function ShellBootstrap():Promise<appshell.BootstrapResponse>;

export function ShellEmitDiagnosticsProbe():Promise<appshell.ProbeResponse>;

export function UpdateCheck():Promise<contracts.UpdateCheckResponse>;

export function WorkspaceActive():Promise<contracts.WorkspaceActiveResponse>;

export function WorkspaceClose():Promise<contracts.WorkspaceCloseResponse>;

export function WorkspaceCreate(arg1:contracts.WorkspaceCreateInput):Promise<contracts.WorkspaceResponse>;

export function WorkspaceDelete():Promise<contracts.WorkspaceCloseResponse>;

export function WorkspaceOpen(arg1:string):Promise<contracts.WorkspaceResponse>;

export function WorkspaceSave(arg1:contracts.WorkspaceSaveInput):Promise<contracts.WorkspaceResponse>;

export function WorkspaceValidate(arg1:contracts.WorkspaceValidateInput):Promise<contracts.WorkspaceValidateResponse>;
